project_id = "ztvvhrvjbboetwxyuzxj"

[functions.admin-invite]
verify_jwt = false

[functions.ask-doubt]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-study-plan]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.sms-helpdesk]
verify_jwt = false
